baseURL: "htttps://yashgovilkar.github.io/portfolio/"
languageCode: en-us
title: Yash Govilkar
theme: PaperMod

params:
  keywords: ["Yash Govilkar","Portfolio"]

services:
  googleAnalytics:
    ID: G-HHXTMB7R2T